--- #YAML:1.0
name:               Padre-Plugin-Shell-Base
version:            0.13
abstract:           A base class for Padre plugins.
author:
    - Gregory Siems <gsiems@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Temp:  0
    Padre:       0.43
    Test::More:  0
    YAML:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
